server:
  port: 8080 # 서버 포트를 기본 포트로 설정
  servlet:
    session:
      timeout: 30m

spring:
  application:
    name: sprignsample
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  session:
    store-type: redis
    redis:
      flush-mode: immediate # 변경 사항을 즉시 Redis에 반영
      namespace: session
  data:
    redis:
      host: localhost
      port: 6379
      password: yourpassword
      timeout: 60s
      # 추가 설정: Redis 연결 풀 및 timeout 설정

app:
  jwt:
    secret: WSvJMIL2xIePrVtevkfrY6WAIZxuaMaOV2RgSNsGVkVxu/3f36eo+m+jqnXjbNjXt0XPwS73g9VbeHg9wL+bdg==
    expiration: 180000

# 추가 설정: 로깅 설정
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
  file:
    name: logs/spring.log

# 추가 설정: CORS 설정 (필요 시)
cors:
  allowed-origins: "*"
  allowed-methods: "GET,POST,PUT,DELETE"
  allowed-headers: "*"

# 추가 설정: 데이터 소스 설정 (필요 시)
# spring:
#   datasource:
#     url: jdbc:mysql://localhost:3306/yourdatabase
#     username: yourusername
#     password: yourpassword
#     driver-class-name: com.mysql.cj.jdbc.Driver
#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true
#     properties:
#       hibernate:
#         format_sql: true
#         use_sql_comments: true
